// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzN2DlRjIqQ7YQKg6jKjbQD6SFk6qNTM',
    appId: '1:222531353080:android:c60a13a97902c3f5',
    messagingSenderId: '222531353080',
    projectId: 'degreednative-android-64c3f',
    databaseURL: 'https://degreednative-android-64c3f.firebaseio.com',
    storageBucket: 'degreednative-android-64c3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrXMDMTA_EhromFgoAM9QYRqKAoKB-tuc',
    appId: '1:222531353080:ios:aef25c49250f9940',
    messagingSenderId: '222531353080',
    projectId: 'degreednative-android-64c3f',
    databaseURL: 'https://degreednative-android-64c3f.firebaseio.com',
    storageBucket: 'degreednative-android-64c3f.appspot.com',
    androidClientId:
        '222531353080-4g97lo2jnorckqloap957uiahku6k0ku.apps.googleusercontent.com',
    iosClientId:
        '222531353080-9nj90kflf8oqijt8k4fm977h3lj2hjei.apps.googleusercontent.com',
    iosBundleId: 'com.degreed.Degreed',
  );
}
